# environment: en Docker Compose → configuración a nivel de contenedor. Inyecta esas variables de entorno antes de que arranque la app 
# (o configura directamente otros contenedores, como MySQL, que las lee él mismo para crearse).
#
# Conexión entre compose y application.properties: Compose define el valor (ej. DB_URL)
# → Docker lo pasa como variable de entorno al contenedor → Spring Boot lo lee en application.properties y lo usa.

# Nombre del conjunto de servicios Docker Compose
name: microservicios-carro-moto

# Definición de los contenedores/servicios
services:

  # =========================
  # MICROSERVICIO USUARIO
  # =========================
  usuario-service:

    # Imagen Docker que se utilizará para crear el contenedor
    image: nicolasmicros/usuario-service:${VERSION_IMAGEN}

    # Nombre fijo del contenedor
    container_name: usuario-service-container

    # Puerto host : puerto interno del contenedor
    ports:
      - "8006:8006"

    # en el environment del Compose crea Variables de entorno que luego leerá Spring Boot,
    # es decir recibe variables de entorno de jenkins para crear sus variables de entorno.
    # Y jenkins las crea en el script del pepeline(JenkinsFile-docker) en la seccion withEnv .
    # Una variable de entorno. Se definen una vez y están disponibles en cualquier punto del programa sin tener que pasarlas como parámetro explícito.
    # Docker inyecta esas variables como variables de entorno del sistema operativo dentro del contenedor, antes incluso de que arranque tu JAR
    environment:

      # Versión de la imagen desplegada, se ha inicializado en el Jenkinsfile-docker con el valor introducido en el parámetro =>  "USUARIO_VERSION=${params.DOCKER_VERSION}"
      VERSION_IMAGEN: ${VERSION_IMAGEN:-LOCAL}

      # Origen del despliegue, se ha inicializado en el Jenkinsfile-docker a pelo => "DEPLOY_ORIGIN=Jenkins-Despliegue JAR en Contenedor"
      DEPLOY_ORIGIN: ${DEPLOY_ORIGIN:-Manual}
      
      # No es necesario pasar GIT_TAG por Compose porque ya se guarda
      # en la imagen desde el Dockerfile mediante ARG + ENV.
        # GIT_TAG: ${GIT_TAG:-desconocido}
      
      # Estas dos variables las utilizamos para que Spring Security y JWT funcionen dentro del contenedor Docker.
      # DEMO_PASSWORD sirve para comprobar el login;
      #  JWT_SECRET sirve para firmar y validar el token que generamos después del login.
      # Clave de firma de los tokens JWT, recibida desde Jenkins
      JWT_SECRET: ${JWT_SECRET:?Falta JWT_SECRET}
      # Contraseña del usuario demo, recibida desde Jenkins
      DEMO_PASSWORD: ${DEMO_PASSWORD:?Falta DEMO_PASSWORD}

      # Activa el perfil Docker de Spring
      SPRING_PROFILES_ACTIVE: docker

      # Puerto interno donde escuchará usuario-service
      SERVER_PORT: 8006

      # URL interna del microservicio carro
      CARRO_SERVICE_URL: http://carro-service:8007

      # URL interna del microservicio moto
      MOTO_SERVICE_URL: http://moto-service:8008

      # URL de conexión a MySQL
      DB_URL: jdbc:mysql://mysql-usuarios:3306/usuariosdb

      DB_USER: usuario
      DB_PASSWORD: usuario123
      DDL_AUTO: update
      SQL_INIT_MODE: never

  # Etiquetas informativas que Docker guarda en el contenedor
    labels:

      # Origen del despliegue: Jenkins si recibe la variable; Manual por defecto
      despliegue.origen: ${DEPLOY_ORIGIN:-Manual}

      # Entorno fijo: siempre DES
      despliegue.entorno: DES

    # Servicios que deben arrancar previamente
    depends_on:
      - carro-service
      - moto-service
      - mysql-usuarios

    # Conecta este contenedor a la red común
    networks:
      - red-microservicios


  # =========================
  # MICROSERVICIO CARRO
  # =========================
  carro-service:

    # Imagen Docker del microservicio carro
    image: nicolasmicros/carro-service:1.0

    # Nombre del contenedor
    container_name: carro-service-container

    # Puerto host : puerto interno
    ports:
      - "8007:8007"

    # Configuración del puerto de Spring Boot
    environment:
      SERVER_PORT: 8007

    # Red Docker compartida
    networks:
      - red-microservicios


  # =========================
  # MICROSERVICIO MOTO
  # =========================
  moto-service:

    # Imagen Docker del microservicio moto
    image: nicolasmicros/moto-service:1.0

    # Nombre del contenedor
    container_name: moto-service-container

    # Puerto host : puerto interno
    ports:
      - "8008:8008"

    # Configuración del puerto de Spring Boot
    environment:
      SERVER_PORT: 8008

    # Red Docker compartida
    networks:
      - red-microservicios


  # =========================
  # BASE DE DATOS MYSQL
  # =========================
  mysql-usuarios:

    # Imagen oficial de MySQL versión 8
    image: mysql:8

    # Nombre del contenedor
    container_name: mysql-usuarios-container

    # Variables utilizadas para crear la base de datos
    environment:

      # Contraseña del usuario root
      MYSQL_ROOT_PASSWORD: root

      # Base de datos que se crea al arrancar
      MYSQL_DATABASE: usuariosdb

      # Usuario de aplicación
      MYSQL_USER: usuario

      # Contraseña del usuario de aplicación
      MYSQL_PASSWORD: usuario123

    # Puerto MySQL host : contenedor
    ports:
      - "3306:3306"

    # Guarda los datos fuera del contenedor
    volumes:
      - mysql-usuarios-data:/var/lib/mysql

    # Conecta MySQL a la misma red que los microservicios
    networks:
      - red-microservicios


# =========================
# RED DOCKER
# =========================
networks:

  # Red privada para que los contenedores se comuniquen por nombre
  red-microservicios:

    # Tipo de red estándar de Docker
    driver: bridge


# =========================
# VOLUMENES
# =========================
volumes:

  # Volumen persistente para conservar los datos de MySQL
  mysql-usuarios-data: